language: node_js
deploy:
  api_key:
    secure: dZVVQeUlZf6Ut2RSae/fw/W4luYYRyN0/DGxycb82r2PxBDrTyv/yCLspYQVaz/0+bsc+LtqFksuIaUuAeuOSohu3pX4LkSIJpcS0YhUzpXrvPjRWMWaCWyw7rTam+9P06XJXAUCbh5Iqo6ma4KGYsPc4lOXv91G8fescDiZ6bk=
  provider: npm
  email: john@mclear.co.uk
